# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1193c7ca1845c856099223e7d986a74efed1c34462803e4c2bb18994b018304571070bdb2db0c43b3dd4f6f0cca41e387ab05ccd8a31486fb0f1f088805dab4c

test:
  secret_key_base: 5b6c386a06e55209d1b893d57d2f1aae9c41bab440c513c0113d42076cdb7fdad5dac48655bee41fc70c70ca4bed26001bfbb3b27584bc360a3b386e5467c313

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
